# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x1c\n\x08Question\x12\x10\n\x08question\x18\x01 \x01(\t\"\x18\n\x06\x41nswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t23\n\x0eQuestionAnswer\x12!\n\x0b\x41skQuestion\x12\t.Question\x1a\x07.Answerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_QUESTION']._serialized_start=14
  _globals['_QUESTION']._serialized_end=42
  _globals['_ANSWER']._serialized_start=44
  _globals['_ANSWER']._serialized_end=68
  _globals['_QUESTIONANSWER']._serialized_start=70
  _globals['_QUESTIONANSWER']._serialized_end=121
# @@protoc_insertion_point(module_scope)
